name: Scheduled script

on:
  schedule:
  - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: "requirements.txt"

    - name: Execute script
      run: python rss_scraper-2.py
